version: '3'

services:
  elrond:
    build:
      context: ./
      dockerfile: ./docker/elrond/Dockerfile

    command: bash -c "go run cmd/node/main.go -port 4000 -max-allowed-peers 4 -private-key \"ZBis8aK5I66x1hwD+fE8sIw2nwQR5EBlTM8EiAOLZwE=\""
    ports:
      - 8080:8080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=elrond-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms9g -Xmx9g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - bcoin

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    container_name: kibana
    hostname: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - bcoin

  head:
    image: mobz/elasticsearch-head:5
    container_name: head
    ports:
      - 9100:9100
    networks:
      - bcoin
  filebeat:
    build: docker/filebeat
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      LOGSTASH_PORT: ${LOGSTASH_PORT}
      INDEX: ${ELASTIC_INDEX}
    volumes:
    - ./docker/filebeat/filebeat.yml:/filebeat.yml
    - ./docker/filebeat/logstash-beats.crt:/etc/pki/tls/certs/logstash-beats.crt
    - ${ELROND_LOG_LOCATION}:/elogs