[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    MinUnstakeTokensValue = "10000000000000000000" #10eGLD
    UnBondPeriod = 2400
    UnBondPeriodInEpochs = 2
    MinStepValue = "100000000000000000000"
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 2169
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = true

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    OwnerAddress = "erd1yy4hnuugmd3245m4d0qxlsgzqv55yeuu5y5r99p8lcj2436vv0nq6drqhc"

[GovernanceSystemSCConfig]
    FirstWhitelistedAddress = "erd1vxy22x0fj4zv6hktmydg8vpfh6euv02cz4yg0aaws6rrad5a5awqgqky80" #should use a multisign contract instead of a wallet address
    [GovernanceSystemSCConfig.V1]
        NumNodes           = 500
        ProposalCost       = "5000000000000000000" #5 eGLD
        MinQuorum          = 400
        MinPassThreshold   = 300
        MinVetoThreshold   = 50
    [GovernanceSystemSCConfig.Active]
        ProposalCost       = "5000000000000000000" #5 eGLD
        MinQuorum          = "500000000000" # MinQuorum is equal to 10*sqrt(NodePrice)
        MinPassThreshold   = "251000000000"
        MinVetoThreshold   = "249000000000"

[DelegationManagerSystemSCConfig]
    MinCreationDeposit = "1250000000000000000000" #1.25K eGLD
    MinStakeAmount = "1000000000000000000" #1 eGLD
    ConfigChangeAddress = "erd1dfrskqy096ly3zcgu4mtxkc5cv3ehgzc0fxq75m5a2uy7cg8f05q3766nv" #should use a multisign contract instead of a wallet address

[DelegationSystemSCConfig]
    MinServiceFee  = 0
    MaxServiceFee  = 10000
