[StakingSystemSCConfig]
    GenesisNodePrice = "2500000000000000000000" #2.5K eGLD
    MinStakeValue = "100000000000000000000" #100 eGLD
    UnBondPeriod = 144000
    MinStepValue = "100000000000000000000"
    AuctionEnableEpoch = 1000000
    StakeEnableEpoch = 1000000
    NumRoundsWithoutBleed = 100
    MaximumPercentageToBleed = 0.5
    BleedPercentagePerRound = 0.00001
    MaxNumberOfNodesForStake = 2169
    NodesToSelectInAuction = 2169
    UnJailValue = "2500000000000000000" #0.1% of genesis node price
    ActivateBLSPubKeyMessageVerification = false

[ESDTSystemSCConfig]
    BaseIssuingCost = "5000000000000000000" #5 eGLD
    OwnerAddress = "erd1ze6pgefwc7mdx0rhje3h50kkgt26ut3gx8ytezndkz8fjcf96gsqsd7ugw"
    EnabledEpoch = 1000000

[GovernanceSystemSCConfig]
    ProposalCost = "5000000000000000000" #5 eGLD
    NumNodes     = 500
    MinQuorum    = 400
    MinPassThreshold = 300
    MinVetoThreshold = 50
    EnabledEpoch = 1000000
